extend = { path = "../cargo-make/main.toml" }

[tasks.setup-node]
env = { SETUP_NODE = false }
condition = { env_true = ["SETUP_NODE"] }

[tasks.build]
command = "cargo"
args = ["+nightly", "build-all-features"]
install_crate = "cargo-all-features"

[tasks.check]
command = "cargo"
args = ["+nightly", "check-all-features"]
install_crate = "cargo-all-features"
