//! A variety of DOM utility functions.

use or_poisoned::OrPoisoned;
#[cfg(debug_assertions)]
use reactive_graph::diagnostics::SpecialNonReactiveZone;
use reactive_graph::owner::Owner;
use send_wrapper::SendWrapper;
use std::time::Duration;
use tachys::html::event::EventDescriptor;
#[cfg(feature = "tracing")]
use tracing::instrument;
use wasm_bindgen::{JsCast, JsValue, UnwrapThrowExt, prelude::Closure};

thread_local! {
    pub(crate) static WINDOW: web_sys::Window = web_sys::window().unwrap_throw();

    pub(crate) static DOCUMENT: web_sys::Document = web_sys::window().unwrap_throw().document().unwrap_throw();
}

/// Returns the [`Window`](https://developer.mozilla.org/en-US/docs/Web/API/Window).
///
/// This is cached as a thread-local variable, so calling `window()` multiple times
/// requires only one call out to JavaScript.
pub fn window() -> web_sys::Window {
    WINDOW.with(Clone::clone)
}

/// Returns the [`Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document).
///
/// This is cached as a thread-local variable, so calling `document()` multiple times
/// requires only one call out to JavaScript.
pub fn document() -> web_sys::Document {
    DOCUMENT.with(Clone::clone)
}

/// Sets a property on a DOM element.
pub fn set_property(
    el: &web_sys::Element,
    prop_name: &str,
    value: &Option<JsValue>,
) {
    let key = JsValue::from_str(prop_name);
    match value {
        Some(value) => _ = js_sys::Reflect::set(el, &key, value),
        None => _ = js_sys::Reflect::delete_property(el, &key),
    };
}

/// Gets the value of a property set on a DOM element.
#[doc(hidden)]
pub fn get_property(
    el: &web_sys::Element,
    prop_name: &str,
) -> Result<JsValue, JsValue> {
    let key = JsValue::from_str(prop_name);
    js_sys::Reflect::get(el, &key)
}

/// Returns the current [`window.location`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location).
pub fn location() -> web_sys::Location {
    window().location()
}

/// Current [`window.location.hash`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location)
/// without the beginning #.
pub fn location_hash() -> Option<String> {
    if is_server() {
        None
    } else {
        location()
            .hash()
            .ok()
            .map(|hash| match hash.chars().next() {
                Some('#') => hash[1..].to_string(),
                _ => hash,
            })
    }
}

/// Current [`window.location.pathname`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location).
pub fn location_pathname() -> Option<String> {
    if is_server() {
        None
    } else {
        location().pathname().ok()
    }
}

/// Helper function to extract [`Event.target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target)
/// from any event.
pub fn event_target<T>(event: &web_sys::Event) -> T
where
    T: JsCast,
{
    event.target().unwrap_throw().unchecked_into::<T>()
}

/// Helper function to extract `event.target.value` from an event.
///
/// This is useful in the `on:input` or `on:change` listeners for an `<input>` element.
pub fn event_target_value<T>(event: &T) -> String
where
    T: JsCast,
{
    event
        .unchecked_ref::<web_sys::Event>()
        .target()
        .unwrap_throw()
        .unchecked_into::<web_sys::HtmlInputElement>()
        .value()
}

/// Helper function to extract `event.target.checked` from an event.
///
/// This is useful in the `on:change` listeners for an `<input type="checkbox">` element.
pub fn event_target_checked(ev: &web_sys::Event) -> bool {
    ev.target()
        .unwrap_throw()
        .unchecked_into::<web_sys::HtmlInputElement>()
        .checked()
}

/// Handle that is generated by [request_animation_frame] and can
/// be used to cancel the animation frame request.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AnimationFrameRequestHandle(i32);

impl AnimationFrameRequestHandle {
    /// Cancels the animation frame request to which this refers.
    ///
    /// The associated callback is freed when the reactive scope that created
    /// the request is cleaned up (see [`request_animation_frame`]).
    /// See [`cancelAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame)
    pub fn cancel(&self) {
        _ = window().cancel_animation_frame(self.0);
    }
}

// Wraps a one-shot `FnOnce` in a `Closure`. The JS-callable shell is reusable
// (invoking it more than once is a silent no-op); the captured data is dropped
// the first time it runs. The returned `Closure` is owned by the caller, which
// decides how to free it (see `own_closure`).
fn closure_once(cb: impl FnOnce() + 'static) -> Closure<dyn FnMut()> {
    let mut wrapped_cb: Option<Box<dyn FnOnce()>> = Some(Box::new(cb));
    Closure::new(move || {
        if let Some(cb) = wrapped_cb.take() {
            cb()
        }
    })
}

/// The four kinds of scheduled JS callback, so a single non-generic cleanup
/// path can cancel any of them. Keeping this one closure type (rather than four
/// distinct ones) means [`Owner::on_cleanup`] is monomorphized only once.
#[derive(Clone, Copy)]
enum TimerKind {
    AnimationFrame,
    IdleCallback,
    Timeout,
    Interval,
}

/// Cancels a scheduled callback by kind and id. The ids are widened to `i64` so
/// every kind shares the same [`own_closure`] cleanup closure; they are narrowed
/// back to the exact type each `web-sys` API expects.
fn cancel_timer(kind: TimerKind, id: i64) {
    let window = window();
    match kind {
        TimerKind::AnimationFrame => {
            _ = window.cancel_animation_frame(id as i32);
        }
        TimerKind::IdleCallback => window.cancel_idle_callback(id as u32),
        TimerKind::Timeout => window.clear_timeout_with_handle(id as i32),
        TimerKind::Interval => window.clear_interval_with_handle(id as i32),
    }
}

/// Hands ownership of a scheduled callback's `Closure` to the reactive ownership
/// tree instead of leaking it to the JS engine's GC.
///
/// The `web-sys` scheduling APIs only return an integer id, but the `Closure`
/// must stay alive until the browser is done with it:
///
/// - If a reactive [`Owner`] is active, the closure is freed when that owner is
///   cleaned up (e.g. the component unmounts) — deterministic cleanup via the
///   framework's own lifecycle. The cleanup [`cancel_timer`]s first, so the
///   browser can never invoke a freed closure: a scheduled callback does not
///   outlive the scope that created it.
/// - With no owner to attach to (e.g. scheduled outside any reactive scope,
///   such as from within another timer's callback), the closure is handed to
///   the JS engine via `into_js_value`, which keeps it alive until the callback
///   fires / the timer is cancelled and then reclaims it via GC. This preserves
///   Leptos's historical behaviour for those call sites.
fn own_closure(kind: TimerKind, id: i64, closure: Closure<dyn FnMut()>) {
    if Owner::current().is_some() {
        let closure = SendWrapper::new(closure);
        Owner::on_cleanup(move || {
            cancel_timer(kind, id);
            drop(closure);
        });
    } else {
        let _ = closure.into_js_value();
    }
}

/// Converts a [`Duration`] into the millisecond delay expected by
/// `setTimeout`/`setInterval`.
///
/// The HTML standard types the timer delay as a signed 32-bit integer and
/// clamps any larger value to `i32::MAX` rather than rejecting it (WHATWG HTML
/// §8.6 "Timers"). `Duration::as_millis` returns a `u128`, so a delay longer
/// than ~24.85 days would overflow an `i32`. We mirror the browser's clamping
/// behaviour instead of overflowing.
fn duration_to_ms(duration: Duration) -> i32 {
    duration.as_millis().min(i32::MAX as u128) as i32
}

/// Runs the given function between the next repaint using
/// [`Window.requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame),
/// returning a cancelable handle.
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
#[cfg_attr(feature = "tracing", instrument(level = "trace", skip_all))]
#[inline(always)]
pub fn request_animation_frame(
    cb: impl FnOnce() + 'static,
) -> Result<AnimationFrameRequestHandle, JsValue> {
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn raf(
        closure: Closure<dyn FnMut()>,
    ) -> Result<AnimationFrameRequestHandle, JsValue> {
        let id = window()
            .request_animation_frame(closure.as_ref().unchecked_ref())?;
        own_closure(TimerKind::AnimationFrame, id as i64, closure);
        Ok(AnimationFrameRequestHandle(id))
    }

    raf(closure_once(cb))
}

/// Handle that is generated by [request_idle_callback] and can be
/// used to cancel the idle callback.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct IdleCallbackHandle(u32);

impl IdleCallbackHandle {
    /// Cancels the idle callback to which this refers.
    ///
    /// The associated callback is freed when the reactive scope that created
    /// the request is cleaned up (see [`request_idle_callback`]).
    /// See [`cancelIdleCallback()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelIdleCallback)
    pub fn cancel(&self) {
        window().cancel_idle_callback(self.0);
    }
}

/// Queues the given function during an idle period using
/// [`Window.requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestIdleCallback),
/// returning a cancelable handle.
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
#[cfg_attr(feature = "tracing", instrument(level = "trace", skip_all))]
#[inline(always)]
pub fn request_idle_callback(
    cb: impl FnOnce() + 'static,
) -> Result<IdleCallbackHandle, JsValue> {
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn ric(
        closure: Closure<dyn FnMut()>,
    ) -> Result<IdleCallbackHandle, JsValue> {
        let id =
            window().request_idle_callback(closure.as_ref().unchecked_ref())?;
        own_closure(TimerKind::IdleCallback, id as i64, closure);
        Ok(IdleCallbackHandle(id))
    }

    ric(closure_once(cb))
}

/// A microtask is a short function which will run after the current task has
/// completed its work and when there is no other code waiting to be run before
/// control of the execution context is returned to the browser's event loop.
///
/// Microtasks are especially useful for libraries and frameworks that need
/// to perform final cleanup or other just-before-rendering tasks.
///
/// [MDN queueMicrotask](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask)
///
/// <div class="warning">The task is called outside of the ownership tree, this means that if you want to access for example the context you need to reestablish the owner.</div>
pub fn queue_microtask(task: impl FnOnce() + 'static) {
    tachys::renderer::dom::queue_microtask(task);
}

/// Handle that is generated by [set_timeout] and can be used to clear the timeout.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct TimeoutHandle(i32);

impl TimeoutHandle {
    /// Cancels the timeout to which this refers.
    ///
    /// The associated callback is freed when the reactive scope that created
    /// the timeout is cleaned up (see [`set_timeout`]).
    /// See [`clearTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout)
    pub fn clear(&self) {
        window().clear_timeout_with_handle(self.0);
    }
}

/// Executes the given function after the given duration of time has passed, returning a cancelable handle.
/// [`setTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout).
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
#[cfg_attr(
  feature = "tracing",
  instrument(level = "trace", skip_all, fields(duration = ?duration))
)]
#[inline(always)]
pub fn set_timeout(
    cb: impl FnOnce() + 'static,
    duration: Duration,
) -> Result<TimeoutHandle, JsValue> {
    #[cfg(debug_assertions)]
    let cb = || {
        let _z = SpecialNonReactiveZone::enter();
        cb();
    };

    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn st(
        closure: Closure<dyn FnMut()>,
        duration: Duration,
    ) -> Result<TimeoutHandle, JsValue> {
        let id = window()
            .set_timeout_with_callback_and_timeout_and_arguments_0(
                closure.as_ref().unchecked_ref(),
                duration_to_ms(duration),
            )?;
        own_closure(TimerKind::Timeout, id as i64, closure);
        Ok(TimeoutHandle(id))
    }

    st(closure_once(cb), duration)
}

/// "Debounce" a callback function. This will cause it to wait for a period of `delay`
/// after it is called. If it is called again during that period, it will wait
/// `delay` before running, and so on. This can be used, for example, to wrap event
/// listeners to prevent them from firing constantly as you type.
///
/// ```
/// use leptos::{leptos_dom::helpers::debounce, logging::log, prelude::*, *};
///
/// #[component]
/// fn DebouncedButton() -> impl IntoView {
///     let delay = std::time::Duration::from_millis(250);
///     let on_click = debounce(delay, move |_| {
///         log!("...so many clicks!");
///     });
///
///     view! {
///       <button on:click=on_click>"Click me"</button>
///     }
/// }
/// ```
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
pub fn debounce<T: 'static>(
    delay: Duration,
    mut cb: impl FnMut(T) + 'static,
) -> impl FnMut(T) {
    use std::sync::{Arc, RwLock};

    #[cfg(debug_assertions)]
    #[allow(unused_mut)]
    let mut cb = move |value| {
        let _z = SpecialNonReactiveZone::enter();
        cb(value);
    };

    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    #[allow(unused_mut)]
    let mut cb = move |value| {
        let _guard = span.enter();
        cb(value);
    };

    let cb = Arc::new(RwLock::new(cb));
    let timer = Arc::new(RwLock::new(None::<TimeoutHandle>));

    Owner::on_cleanup({
        let timer = Arc::clone(&timer);
        move || {
            if let Some(timer) = timer.write().or_poisoned().take() {
                timer.clear();
            }
        }
    });

    move |arg| {
        if let Some(timer) = timer.write().unwrap().take() {
            timer.clear();
        }
        let handle = set_timeout(
            {
                let cb = Arc::clone(&cb);
                move || {
                    cb.write().unwrap()(arg);
                }
            },
            delay,
        );
        if let Ok(handle) = handle {
            *timer.write().or_poisoned() = Some(handle);
        }
    }
}

/// Handle that is generated by [set_interval] and can be used to clear the interval.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct IntervalHandle(i32);

impl IntervalHandle {
    /// Cancels the repeating event to which this refers.
    ///
    /// The associated callback is freed when the reactive scope that created
    /// the interval is cleaned up (see [`set_interval`]).
    /// See [`clearInterval()`](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval)
    pub fn clear(&self) {
        window().clear_interval_with_handle(self.0);
    }
}

/// Repeatedly calls the given function, with a delay of the given duration between calls,
/// returning a cancelable handle.
/// See [`setInterval()`](https://developer.mozilla.org/en-US/docs/Web/API/setInterval).
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
#[cfg_attr(
  feature = "tracing",
  instrument(level = "trace", skip_all, fields(duration = ?duration))
)]
#[inline(always)]
pub fn set_interval(
    cb: impl Fn() + 'static,
    duration: Duration,
) -> Result<IntervalHandle, JsValue> {
    #[cfg(debug_assertions)]
    let cb = move || {
        let _z = SpecialNonReactiveZone::enter();
        cb();
    };
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn si(
        cb: Box<dyn FnMut()>,
        duration: Duration,
    ) -> Result<IntervalHandle, JsValue> {
        let closure = Closure::wrap(cb);
        let id = window()
            .set_interval_with_callback_and_timeout_and_arguments_0(
                closure.as_ref().unchecked_ref(),
                duration_to_ms(duration),
            )?;
        own_closure(TimerKind::Interval, id as i64, closure);
        Ok(IntervalHandle(id))
    }

    si(Box::new(cb), duration)
}

/// Adds an event listener to the `Window`, typed as a generic `Event`,
/// returning a cancelable handle.
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
#[cfg_attr(
  feature = "tracing",
  instrument(level = "trace", skip_all, fields(event_name = %event_name))
)]
#[inline(always)]
pub fn window_event_listener_untyped(
    event_name: &str,
    cb: impl Fn(web_sys::Event) + 'static,
) -> WindowListenerHandle {
    #[cfg(debug_assertions)]
    let cb = move |e| {
        let _z = SpecialNonReactiveZone::enter();
        cb(e);
    };
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move |e| {
        let _guard = span.enter();
        cb(e);
    };

    if !is_server() {
        #[inline(never)]
        fn wel(
            cb: Box<dyn FnMut(web_sys::Event)>,
            event_name: &str,
        ) -> WindowListenerHandle {
            let cb = Closure::wrap(cb).into_js_value();
            _ = window().add_event_listener_with_callback(
                event_name,
                cb.unchecked_ref(),
            );
            let event_name = event_name.to_string();
            let cb = SendWrapper::new(cb);
            WindowListenerHandle(Box::new(move || {
                _ = window().remove_event_listener_with_callback(
                    &event_name,
                    cb.unchecked_ref(),
                );
            }))
        }

        wel(Box::new(cb), event_name)
    } else {
        WindowListenerHandle(Box::new(|| ()))
    }
}

/// Creates a window event listener from a typed event, returning a
/// cancelable handle.
/// ```
/// use leptos::{
///     ev, leptos_dom::helpers::window_event_listener, logging::log,
///     prelude::*,
/// };
///
/// #[component]
/// fn App() -> impl IntoView {
///     let handle = window_event_listener(ev::keypress, |ev| {
///         // ev is typed as KeyboardEvent automatically,
///         // so .code() can be called
///         let code = ev.code();
///         log!("code = {code:?}");
///     });
///     on_cleanup(move || handle.remove());
/// }
/// ```
///
/// ### Note about Context
///
/// The callback is called outside of the reactive ownership tree. This means that it does not have access to context via [`use_context`](reactive_graph::owner::use_context). If you want to use context inside the callback, you should either call `use_context` in the body of the component, and move the value into the callback, or access the current owner inside the component body using [`Owner::current`](reactive_graph::owner::Owner::current) and reestablish it in the callback with [`Owner::with`](reactive_graph::owner::Owner::with).
pub fn window_event_listener<E: EventDescriptor + 'static>(
    event: E,
    cb: impl Fn(E::EventType) + 'static,
) -> WindowListenerHandle
where
    E::EventType: JsCast,
{
    window_event_listener_untyped(&event.name(), move |e| {
        cb(e.unchecked_into::<E::EventType>())
    })
}

/// A handle that can be called to remove a global event listener.
pub struct WindowListenerHandle(Box<dyn FnOnce() + Send + Sync>);

impl core::fmt::Debug for WindowListenerHandle {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_tuple("WindowListenerHandle").finish()
    }
}

impl WindowListenerHandle {
    /// Removes the event listener.
    pub fn remove(self) {
        (self.0)()
    }
}

/// Returns `true` if the current environment is a server.
pub fn is_server() -> bool {
    #[cfg(feature = "hydration")]
    {
        Owner::current_shared_context()
            .map(|sc| !sc.is_browser())
            .unwrap_or(false)
    }
    #[cfg(not(feature = "hydration"))]
    {
        false
    }
}

/// Returns `true` if the current environment is a browser.
pub fn is_browser() -> bool {
    !is_server()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn duration_to_ms_passes_small_durations_through() {
        assert_eq!(duration_to_ms(Duration::ZERO), 0);
        assert_eq!(duration_to_ms(Duration::from_millis(250)), 250);
        assert_eq!(duration_to_ms(Duration::from_secs(1)), 1000);
    }

    #[test]
    fn duration_to_ms_clamps_durations_over_i32_max() {
        // 30 days is 2_592_000_000 ms, which exceeds i32::MAX (2_147_483_647).
        // It must clamp to i32::MAX, matching the browser, rather than
        // overflowing the `u128 -> i32` conversion.
        let thirty_days = Duration::from_secs(60 * 60 * 24 * 30);
        assert!(thirty_days.as_millis() > i32::MAX as u128);
        assert_eq!(duration_to_ms(thirty_days), i32::MAX);

        // The exact boundary maps to i32::MAX, and one past it still clamps.
        let boundary = Duration::from_millis(i32::MAX as u64);
        assert_eq!(duration_to_ms(boundary), i32::MAX);
        let past_boundary = Duration::from_millis(i32::MAX as u64 + 1);
        assert_eq!(duration_to_ms(past_boundary), i32::MAX);
    }

    // `request_idle_callback` must accept a one-shot closure that moves out of
    // (consumes) its captures, exactly like `request_animation_frame`. The
    // closures below are type-checked at compile time, which is where the
    // `FnOnce` bound is enforced, but they are never invoked, so the DOM is
    // never touched in this headless test. A regression to an `Fn` bound would
    // make this fail to compile.
    #[test]
    fn request_idle_callback_accepts_consuming_closure() {
        let _ric = || {
            let owned = String::from("hello");
            request_idle_callback(move || drop(owned))
        };
        let _raf = || {
            let owned = String::from("hello");
            request_animation_frame(move || drop(owned))
        };
    }
}
