extend = [{ path = "./cargo-make/main.toml" }]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = ""
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
  "animated_show",
  "counter",
  "counter_isomorphic",
  "counters",
  "counters_stable",
  "counter_url_query",
  "counter_without_macros",
  "error_boundary",
  "errors_axum",
  "fetch",
  "hackernews",
  "hackernews_axum",
  "js-framework-benchmark",
  "leptos-tailwind-axum",
  "login_with_token_csr_only",
  "parent_child",
  "router",
  "session_auth_axum",
  "slots",
  "ssr_modes",
  "ssr_modes_axum",
  "suspense_tests",
  "tailwind",
  "tailwind_csr_trunk",
  "timer",
  "todo_app_sqlite",
  "todo_app_sqlite_axum",
  "todo_app_sqlite_viz",
  "todomvc",
]

[tasks.gen-members]
workspace = false
description = "Generate the list of workspace members"
script = '''
examples=$(ls | 
grep -v README.md | 
grep -v Makefile.toml | 
grep -v cargo-make | 
grep -v gtk | 
jq -R -s -c 'split("\n")[:-1]')
echo "CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = $examples"
'''

[tasks.test-runner-report]
workspace = false
description = "report ci test runners for each example - OPTION: [all]"
script = '''
set -emu

BOLD="\e[1m"
GREEN="\e[0;32m"
ITALIC="\e[3m"
YELLOW="\e[0;33m"
RESET="\e[0m"

echo
echo "${YELLOW}Test Runner Report${RESET}"
echo "${ITALIC}Pass the option \"all\" to show all the examples${RESET}"
echo

makefile_paths=$(find . -name Makefile.toml -not -path '*/target/*' |
  sed 's%./%%' |
  sed 's%/Makefile.toml%%' |
  grep -v Makefile.toml |
  sort -u)

start_path=$(pwd)

for path in $makefile_paths; do
  cd $path

  test_runner=

  test_count=$(grep -rl -E "#\[test\]" | wc -l)
  if [ $test_count -gt 0 ]; then
      test_runner="T"
  fi

  while read -r line; do
      case $line in
      *"cucumber"*)
          test_runner=$test_runner"C"
          ;;
      *"rstest"*)
          test_runner=$test_runner"R"
          ;;
      esac
  done <"./Cargo.toml"

  while read -r line; do
    case $line in
      *"wasm-test.toml"*)
          test_runner=$test_runner"W"
        ;;
      *"playwright-test.toml"*)
          test_runner=$test_runner"P"
        ;;
      *"cargo-leptos-test.toml"*)
          test_runner=$test_runner"L"
        ;;
    esac
  done <"./Makefile.toml"

  runners=$(echo ${test_runner} | grep -o . | sort | tr -d "\n") 

  if [ ! -z ${1+x} ]; then
    # Show all examples
    echo "$path ➤ ${BOLD}${runners}${RESET}"
  elif [ ! -z $runners ]; then
    # Filter out examples that do not run tests in `ci`
    echo "$path ➤ ${BOLD}${runners}${RESET}"
  fi

  cd ${start_path}
done
echo
echo "${ITALIC}Runners: C = Cucumber, L = Cargo Leptos, P = Playwright, R = RS Test, T = Cargo, W = WASM${RESET}"
echo
'''

# ALIASES

[tasks.tr]
alias = "test-runner-report"
