extend = [
    { path = "../cargo-make/main.toml" },
    { path = "../cargo-make/cargo-leptos-test.toml" },
]

[tasks.build]
command = "cargo"
args = ["+nightly", "build-all-features"]
install_crate = "cargo-all-features"

[tasks.check]
command = "cargo"
args = ["+nightly", "check-all-features"]
install_crate = "cargo-all-features"
