extend = { path = "../../cargo-make/main.toml" }

[tasks.test]
env = { RUN_AUTOMATICALLY = false }
condition = { env_true = ["RUN_AUTOMATICALLY"] }

[tasks.ci]

[tasks.test-ui]
command = "cargo"
args = [
    "test",
    "--test",
    "app_suite",
    "--",
    "--retry",
    "2",
    "--fail-fast",
    "${@}",
]
