extend = { path = "../../cargo-make/main.toml" }

[tasks.test]
env = { RUN_AUTOMATICALLY = false }
condition = { env_true = ["RUN_AUTOMATICALLY"] }

[tasks.ci]

[tasks.test-ui]
command = "cargo"
args = [
  "nextest",
  "run",
  "--no-tests",
  "warn",
  "--test",
  "app_suite",
  "--",
  "--retry",
  "5",
  "--fail-fast",
  "${@}",
]
