extend = { path = "../../cargo-make/main.toml" }

[tasks.test]
env = { RUN_AUTOMATICALLY = false }
condition = { env_true = ["RUN_AUTOMATICALLY"] }

[tasks.ci]

[tasks.test-ui]
env = { "NEXTEST_NO_TESTS" = "warn" }
command = "cargo"
args = [
  "nextest",
  "run",
  "--test",
  "app_suite",
  "--retries",
  "5",
  "--fail-fast",
  "${@}",
]
