[tasks.check-wasm]
clear = true
dependencies = ["check-hydrate", "check-csr"]

[tasks.check-hydrate]
command = "cargo"
args = [
	"check",
	"--no-default-features",
	"--features=hydrate",
	"--target=wasm32-unknown-unknown",
]

[tasks.check-csr]
command = "cargo"
args = [
	"check",
	"--no-default-features",
	"--features=csr",
	"--target=wasm32-unknown-unknown",
]
