extend = { path = "../cargo-make/main.toml" }

[tasks.check]
clear = true
dependencies = [
  "clippy-each-feature",
  "check-wasm",
  "check-release",
  "check-wasm-release",
]

[tasks.check-wasm]
clear = true
dependencies = ["check-hydrate", "check-csr"]

[tasks.check-wasm-release]
clear = true
dependencies = ["check-hydrate-release", "check-csr-release"]

[tasks.check-hydrate]
command = "cargo"
args = [
  "check",
  "--no-default-features",
  "--features=hydrate",
  "--target=wasm32-unknown-unknown",
]

[tasks.check-csr]
command = "cargo"
args = [
  "check",
  "--no-default-features",
  "--features=csr",
  "--target=wasm32-unknown-unknown",
]

[tasks.check-hydrate-release]
command = "cargo"
args = [
  "check",
  "--release",
  "--no-default-features",
  "--features=hydrate",
  "--target=wasm32-unknown-unknown",
]

[tasks.check-csr-release]
command = "cargo"
args = [
  "check",
  "--release",
  "--no-default-features",
  "--features=csr",
  "--target=wasm32-unknown-unknown",
]

[tasks.check-release]
command = "cargo"
args = ["check", "--release"]
