extend = [
    { path = "../cargo-make/main.toml" },
    { path = "../cargo-make/cargo-leptos-webdriver-test.toml" },
]

[env]
CLIENT_PROCESS_NAME = "suspense_tests"

[tasks.test-ui]
cwd = "./e2e"
command = "cargo"
args = ["make", "test-ui", "${@}"]
