//! Provides a builder and implementation for wholesale configuration of [`axum::Router`].

use crate::{generate_route_list, ErrorHandler, LeptosRoutes};
#[cfg(feature = "default")]
use crate::{
    site_pkg_dir_service, site_pkg_dir_service_route_path, LeptosContextLayer,
};
use axum::{extract::FromRef, Router};
use leptos::{config::LeptosOptions, IntoView};
#[cfg(feature = "default")]
use tower::builder::ServiceBuilder;

pub(crate) mod traits {
    //! Provides the trait for [`RouterConfiguration`].
    use super::*;

    /// This trait is the means to provide different kinds of configuration to the different sets of
    /// generics that may be configured for the underlying concrete type.
    ///
    /// This trait is sealed and cannot be implemented for callers as this exists to encapsulate internal
    /// implementation details.
    #[diagnostic::on_unimplemented(
        label = "incomplete `RouterConfiguration`",
        note = "ensure that `.app()`, `.shell()`, and `.state()` are provided \
                with the required values"
    )]
    pub trait RouterConfiguration<S>: crate::private::Sealed
    where
        S: Clone + Send + Sync + 'static,
        LeptosOptions: FromRef<S>,
    {
        /// Apply the configuration onto the [`Router`].
        fn apply<S2>(self, router: Router<S>) -> Router<S2>;
    }
}

/// A configuration builder that simplifies the set up of a Leptos application onto an Axum router.
///
/// This builder is used in conjunction with [`LeptosRoutes::leptos_route_configure`], please refer to it for
/// a practical example.
///
/// Note that an incomplete configuration should lead to a compilation error rather than a runtime error due
/// to the trait bounds.  The required fields are `app`, `shell`, and `state`.
#[derive(Clone)]
pub struct RouterConfiguration<APP, CX = fn(), SH = (), S = ()> {
    pub(super) app_fn: Option<APP>,
    pub(super) shell: Option<SH>,
    pub(super) state: Option<S>,
    pub(super) extra_cx: Option<CX>,
    #[cfg(feature = "default")]
    pub(super) serve_site_pkg: bool,
    pub(super) error_handler: bool,
}

/// Create a new configuration with all toggles disabled.
impl<APP> Default for RouterConfiguration<APP> {
    fn default() -> Self {
        Self {
            app_fn: None,
            shell: None,
            state: None,
            extra_cx: None,
            #[cfg(feature = "default")]
            serve_site_pkg: false,
            error_handler: false,
        }
    }
}

impl<APP> RouterConfiguration<APP> {
    /// Create a new configuration with all toggles set to the recommended value.
    ///
    /// This enables route to the site pkg [`ServeDir`] service and the [`ErrorHandler`] service as the
    /// fallback handler; also refer to [`.serve_site_pkg`] and [`.error_handler`] for details.
    ///
    /// Use of `RouterConfiguration::default()` disables these by default.
    ///
    /// [`ServeDir`]: tower_http::services::ServeDir
    /// [`.serve_site_pkg`]: RouterConfiguration::serve_site_pkg
    /// [`.error_handler`]: RouterConfiguration::error_handler
    pub fn new() -> Self {
        Self {
            app_fn: None,
            shell: None,
            state: None,
            extra_cx: None,
            #[cfg(feature = "default")]
            serve_site_pkg: true,
            error_handler: true,
        }
    }
}

impl<APP, CX, SH, S> RouterConfiguration<APP, CX, SH, S> {
    /// Provide the `App` to the configuration.  This is required.
    pub fn app<IV>(mut self, app: APP) -> Self
    where
        APP: Fn() -> IV + Clone + Send + Sync + 'static,
        IV: IntoView + 'static,
    {
        self.app_fn = Some(app);
        self
    }

    /// Toggle for the site pkg [`ServeDir`] service; set to `true` to enable.
    ///
    /// When enabled, the underlying `LeptosOptions` will be referenced to create the route to the `ServeDir`
    /// service that will serve the JS/WASM bundle such that the application will be activated on the client.
    ///
    /// [`ServeDir`]: tower_http::services::ServeDir
    #[cfg(feature = "default")]
    pub fn serve_site_pkg(mut self, v: bool) -> Self {
        self.serve_site_pkg = v;
        self
    }

    /// Toggle for the fallback error handler; set to `true` to enable.
    ///
    /// When enabled, the [`ErrorHandler`] service will be applied as the fallback service, so that access to
    /// locations that do not have an active route will instead be rendered using the `shell`, which typically
    /// will render the 404 Not Found page generated by the underlying application.
    pub fn error_handler(mut self, v: bool) -> Self {
        self.error_handler = v;
        self
    }

    /// Configure a new shell function.  This is required.
    ///
    /// Ensure that the argument that will be passed to this function be supplied with [`.state`] to this
    /// builder, and somewhere within its returned view should contain the `App` component set up with this
    /// builder with [`.app`].
    ///
    /// [`.app`]: RouterConfiguration::app
    /// [`.state`]: RouterConfiguration::state
    pub fn shell<SH2, S2, IV>(
        self,
        shell: SH2,
    ) -> RouterConfiguration<APP, CX, SH2, S>
    where
        SH2: Fn(S2) -> IV + Clone + Send + Sync + 'static,
        S2: Clone + Send + Sync + 'static,
        LeptosOptions: FromRef<S2>,
        IV: IntoView + 'static,
    {
        RouterConfiguration {
            app_fn: self.app_fn,
            shell: Some(shell),
            state: self.state,
            extra_cx: self.extra_cx,
            #[cfg(feature = "default")]
            serve_site_pkg: self.serve_site_pkg,
            error_handler: self.error_handler,
        }
    }

    /// Provide an additional context to set up Leptos routes with.  This is optional.
    ///
    /// The provided closure will be applied to all underlying services.
    pub fn with_context<CX2>(
        self,
        extra_cx: CX2,
    ) -> RouterConfiguration<APP, CX2, SH, S>
    where
        CX2: Fn() + 'static + Clone + Send + Sync,
    {
        RouterConfiguration {
            app_fn: self.app_fn,
            shell: self.shell,
            state: self.state,
            extra_cx: Some(extra_cx),
            #[cfg(feature = "default")]
            serve_site_pkg: self.serve_site_pkg,
            error_handler: self.error_handler,
        }
    }

    /// Provide the state.  This is required.
    ///
    /// This must be a value of the same type as the singular argument that will be passed to [`.shell`].
    ///
    /// [`.shell`]: RouterConfiguration::shell
    pub fn state<S2>(self, state: S2) -> RouterConfiguration<APP, CX, SH, S2>
    where
        S2: Clone + Send + Sync + 'static,
        LeptosOptions: FromRef<S2>,
    {
        RouterConfiguration {
            app_fn: self.app_fn,
            shell: self.shell,
            state: Some(state),
            extra_cx: self.extra_cx,
            #[cfg(feature = "default")]
            serve_site_pkg: self.serve_site_pkg,
            error_handler: self.error_handler,
        }
    }
}

impl<APP, CX, SH, S, IV1, IV2> traits::RouterConfiguration<S>
    for RouterConfiguration<APP, CX, SH, S>
where
    APP: Fn() -> IV1 + Clone + Copy + Send + Sync + 'static,
    CX: Fn() + Clone + Copy + Send + Sync + 'static,
    SH: Fn(S) -> IV2 + Clone + Copy + Send + Sync + 'static,
    S: Clone + Send + Sync + 'static,
    LeptosOptions: FromRef<S>,
    IV1: IntoView + 'static,
    IV2: IntoView + 'static,
{
    #[cfg_attr(
        feature = "tracing",
        tracing::instrument(level = "trace", fields(error), skip_all)
    )]
    fn apply<S2>(self, router: Router<S>) -> Router<S2> {
        let app = self.app_fn.expect("an `App` should have been configured");
        let shell = self.shell.expect("a `shell` should have been configured");
        let state = self.state.expect("a `state` should have been configured");
        let extra_cx = self.extra_cx;

        let routes = generate_route_list(app);
        let router = if let Some(extra_cx) = extra_cx {
            router.leptos_routes_with_context(&state, routes, extra_cx, {
                let state = state.clone();
                move || shell(state.clone())
            })
        } else {
            router.leptos_routes(&state, routes, {
                let state = state.clone();
                move || shell(state.clone())
            })
        };

        let error_handler = self.error_handler.then(|| {
            ErrorHandler::new_with_option_context(
                extra_cx,
                shell,
                state.clone(),
            )
        });

        #[cfg(feature = "default")]
        let router = if self.serve_site_pkg {
            let builder = ServiceBuilder::new().option_layer(
                extra_cx.map(LeptosContextLayer::new_with_context),
            );
            let leptos_options = LeptosOptions::from_ref(&state);
            if let Some(error_handler) = error_handler.clone() {
                router.route_service(
                    &site_pkg_dir_service_route_path(&leptos_options),
                    builder.service(
                        site_pkg_dir_service(&leptos_options)
                            .fallback(error_handler),
                    ),
                )
            } else {
                router.route_service(
                    &site_pkg_dir_service_route_path(&leptos_options),
                    builder.service(site_pkg_dir_service(&leptos_options)),
                )
            }
        } else {
            router
        };

        let router = if let Some(error_handler) = error_handler {
            router.fallback_service(error_handler)
        } else {
            router
        };

        router.with_state(state)
    }
}
