extend = [
    { path = "../cargo-make/main.toml" },
    { path = "../cargo-make/wasm-test.toml" },
    { path = "../cargo-make/trunk_server.toml" },
]

[tasks.build]
toolchain = "stable"
command = "cargo"
args = ["build-all-features"]
install_crate = "cargo-all-features"

[tasks.check]
toolchain = "stable"
command = "cargo"
args = ["check-all-features"]
install_crate = "cargo-all-features"
