extend = [
    { path = "../cargo-make/common.toml" },
    { path = "../cargo-make/wasm-web-test.toml" },
]

[tasks.build]
command = "cargo"
args = ["+stable", "build-all-features"]
install_crate = "cargo-all-features"

[tasks.check]
command = "cargo"
args = ["+stable", "check-all-features"]
install_crate = "cargo-all-features"
